/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.planocontas.entity.planoconta;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class PlanoContaAutoCompleteImpl implements PlanoContaAutoComplete {

	private java.util.UUID id;
	
	private String codigo;
	
	private String descricao;
	
	public PlanoContaAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
