/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.planocontas.entity.planoconta;

import com.querydsl.core.types.Predicate;

public interface PlanoContaListFilterPredicate {
	
	Predicate mountAndGetPredicate(PlanoContaListFilter planoContaListFilter);

}

