/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.financeiro.planocontas.entity.planoconta;



public interface PlanoContaAutoComplete {

	java.util.UUID getId();
	
	String getCodigo();
	
	String getDescricao();
	
	void setId(java.util.UUID id);
	
	void setCodigo(String codigo);
	
	void setDescricao(String descricao);

}
